name: luxcore
base: core22
adopt-info: luxcore
version: 0.0.1
issues: https://github.com/rostskadat/LuxCore-snap/issues
website: https://luxcorerender.org/
summary: A physically based and unbiased rendering engine
description: |
  LuxCoreRender is a physically based and unbiased rendering engine. Based on
  state of the art algorithms, LuxCoreRender simulates the flow of light 
  according to physical equations, thus producing realistic images of 
  photographic quality.

  Commands:
    luxcore.luxcoreui: Run luxcoreui
    luxcore.luxcoreconsole: Run luxcoreconsole

grade: devel
confinement: strict
compression: lzo
license: LGPL-2.0-or-later
architectures:
  - build-on: [amd64]

environment:
  LD_LIBRARY_PATH: "$SNAP/usr/lib/:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/:$LD_LIBRARY_PATH"
  GIT_EXEC_PATH: $SNAP/usr/lib/git-core
  GIT_TEMPLATE_DIR: $SNAP/usr/share/git-core/templates
  GIT_CONFIG_NOSYSTEM: 1
  PIP_USER: 1

apps:
  luxcoreui:
    command: usr/bin/luxcoreui
    plugs: &plugs
      - opengl
      - x11
    environment:
      LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/lib
  luxcoreconsole:
    command: usr/bin/luxcoreconsole
    plugs: *plugs
    environment:
      LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/lib

parts:
  # There are no distribution package for OIDIN. We use a precompiled version
  # We should use 
  # $(dpkg-architecture --query DEB_TARGET_GNU_CPU)
  # $(dpkg-architecture --query DEB_TARGET_ARCH_OS)
  # to get 'x86_64' and 'linux'
  oidin:
    plugin: dump
    source: https://github.com/OpenImageDenoise/oidn/releases/download/v2.1.0/oidn-2.1.0.x86_64.linux.tar.gz
    source-type: tar
    stage:
      - include
      - lib/cmake
      - lib/libOpenImageDenoise*

  # This part builds LuxCore and reproduce the custom script available at
  # https://wiki.luxcorerender.org/Compiling_LuxCore#Linux. However
  # distribution package are prefered as well as generating dynamically linked
  # executables.
  luxcore:
    after: [oidin]
    plugin: cmake
    source: https://github.com/LuxCoreRender/LuxCore.git
    build-packages:
      - bison
      - doxygen
      - flex
      - g++
      - git
      - libblosc-dev
      - libboost-all-dev
      - libbz2-dev
      - libembree-dev
      - libgl1-mesa-dev
      - libgtk-3-dev
      - libopencolorio-dev
      - libopenexr-dev
      - libopenimageio-dev
      # - core20: libopenvdb-dev
      - libpng-dev
      - libtbb2-dev # core20: libtbb-dev / version 2020.3-1
      - libtiff5-dev
      - python3-dev
      - python3-pip
    stage-packages:
      # We can obtain the list of snap package with:
      # readelf --wide --dynamic luxcore |grep 'Shared library'|sed -E 's/.*\[(.*)]$/\1/'|xargs dpkg -S|cut -d: -f1|sort -u
      - libblosc1
      - libboost-chrono1.74.0
      - libboost-filesystem1.74.0
      - libboost-iostreams1.74.0
      - libboost-regex1.74.0
      - libboost-serialization1.74.0
      - libboost-thread1.74.0
      - libc6
      - libembree3-3
      - libgcc-s1
      - libgl1
      - libglib2.0-0
      - libglib2.0-dev
      - libgomp1
      - libgtk-3-0
      - libilmbase25
      - libopenimageio2.2
      - libstdc++6
      - libtbb2 # core20: libtbb / version 2020.3-1
      - libx11-6
      - libxcursor1
      - libxi6
      - libxinerama1
      - libxrandr2
      - zlib1g
    override-pull: |
      craftctl default
      craftctl set version=$(git describe --tags --abbrev=10)
      # Adding missing include in boost serialization library
      patch --forward --directory=/ --strip=0 --input=$SNAPCRAFT_PROJECT_DIR/snap/local/patches/patch_001.patch || true
      # Missing conversion in spdlog library
      patch --forward --directory=/ --strip=0 --input=$SNAPCRAFT_PROJECT_DIR/snap/local/patches/patch_002.patch || true
      # Makes sure to use dynamic library instead of static library.
      # Required to get the pyluxcore to link when libboost_thread is not recompilable.
      patch --forward --directory=/ --strip=0 --input=$SNAPCRAFT_PROJECT_DIR/snap/local/patches/patch_003.patch || true
    override-build: |
      set -eux
      # Since there is no install target the default build fails :(
      # We need to reproduce the whole build command found at
      # REF: https://github.com/LuxCoreRender/LinuxCompile.git/build
      # TODO: use $CRAFT_STAGE instead of '/root/parts/oidin/build' (linking 
      #   fails though)
      cmake -G "Unix Makefiles" -Wno-dev \
        -DCMAKE_PREFIX_PATH=/usr/lib/$SNAPCRAFT_ARCH_TRIPLET:/usr/include/$SNAPCRAFT_ARCH_TRIPLET \
        -DOIDN_INCLUDE_PATH:PATH=/root/parts/oidin/build/include \
        -DOIDN_LIBRARY:FILEPATH=/root/parts/oidin/build/lib/libOpenImageDenoise.so \
        -Wno-dev \
        -DCMAKE_INSTALL_PREFIX:PATH=/usr \
        -DCMAKE_BUILD_TYPE=Release \
        -DPYTHON_INCLUDE_DIR:PATH=/usr/include/python3.10 \
        -DPYTHON_LIBRARY:FILEPATH=/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libpython3.10.so \
        $SNAPCRAFT_PART_SRC
      cmake --build $SNAPCRAFT_PART_BUILD --target luxcoreui -- -j2
      cmake --build $SNAPCRAFT_PART_BUILD --target luxcoreconsole -- -j2
      # There is unfortunately no install target :(
      [ -d $SNAPCRAFT_PART_INSTALL/usr/bin ] || mkdir $SNAPCRAFT_PART_INSTALL/usr/bin
      cp -f $SNAPCRAFT_PART_BUILD/bin/luxcoreui $SNAPCRAFT_PART_INSTALL/usr/bin/luxcoreui
      cp -f $SNAPCRAFT_PART_BUILD/bin/luxcoreconsole $SNAPCRAFT_PART_INSTALL/usr/bin/luxcoreconsole
    stage:
      - usr/bin/luxcoreui
      - usr/bin/luxcoreconsole