name: Promote Edge to Beta

on:
  # REF: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_run
  # workflow_run:
  #   workflows:
  #     - Build Edge
  #   types:
  #     - completed
  #   branches:
  #     - main
  schedule:
    - cron: "0 4 * * 0" # Every Sunday at 4:00
  workflow_dispatch: # or manually

jobs:
  promote_edge_to_beta:
    runs-on: ubuntu-latest
    # REF: https://docs.github.com/en/webhooks/webhook-events-and-payloads#workflow_run
    # if: |
    #   (
    #     github.event.workflow_run.event == 'push' &&
    #     github.event.workflow_run.conclusion == 'success'
    #     github.event.workflow_run.tag == 'v*'
    #   )
    steps:
    - uses: actions/checkout@v4
    - run: sudo snap install snapcraft --classic
    - env:
        SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_STORE_CREDENTIALS }}
      run: |
        edge_revision="$(curl -H 'Snap-Device-Series: 16' \
          'https://api.snapcraft.io/v2/snaps/info/luxcore' \
          | jq '."channel-map"[] | select(.channel.name=="edge").revision')"
        snapcraft release luxcore "$edge_revision" beta
