name: Publish Toponaming

on:
  schedule:
    - cron: "0 0 * * *" # Every day at 0:00
  workflow_dispatch: # or manually
    
jobs:
  publish_amd64:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install snapcraft
      run: sudo snap install snapcraft --classic
    - name: install yq
      run: sudo snap install yq
    - name: modify snapcraft.yaml
      run: yq -i '.parts.luxcore.source-branch = "development/toponaming"' snap/snapcraft.yaml
    - name: build snap
      run: |
        sudo snapcraft --destructive-mode
        sudo rm -rf $HOME/.config/snapcraft
    # - uses: snapcore/action-build@v1
    #   id: build
    #   with:
    #     snapcraft-args: "--destructive-mode"
    - name: publish snap
      env:
        SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_STORE_CREDENTIALS }}
      run: snapcraft upload --release='latest/edge/toponaming' luxcore*.snap
    # - uses: snapcore/action-publish@v1
    #   with:
    #     store_login: ${{ secrets.SNAPCRAFT_STORE_CREDENTIALS }}
    #     snap: ${{ steps.build.outputs.snap }}
    #     release: latest/edge/toponaming
